name: M5Stack CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: tool chain setup
      run: |
        sudo apt-get install gcc git wget make libncurses-dev flex bison gperf python python-serial
        wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
        tar zxvf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
        export PATH=./xtensa-esp32-elf/xtensa-esp32-elf/bin:${PATH}
        (cd ./xtensa-esp32-elf && git clone -b v3.1.3 --recursive https://github.com/espressif/esp-idf.git)
        export IDF_PATH=./xtensa-esp32-elf/esp-idf
        ls -laF
        ls -laF ./xtensa-esp32-elf
        ls -laF ${IDF_PATH}
        echo $PATH
 
