name: M5Stack CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker build
      uses: docker://espressif/esp32-ci-env
      run: |
        pwd
        ls -laF
        ls -laF /opt
        ls -laF /github/workspace
